version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
    - build:
        filters:
          branches:
            only: master

jobs:
  build:
    docker:
    - image: cimg/go:1.19
    working_directory: ~/home-info-dashboard

    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout

    # test
    - run: make test

    # build and publish image
    - run: make image-login
    - run: make image-build
    - run: make image-publish
