version: 2.1
jobs:
  build:
    docker:
    - image: circleci/golang:1.13

    branches:
      ignore:
      - develop

    working_directory: /go/src/github.com/JamesClonk/home-info-dashboard

    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout

    # test
    - run: make test

    # build and publish image
    - run: make image-setup
    - run: make image-login
    - run: make image-publish

    # deploy to Swisscom Application Cloud
    - deploy:
        name: appcloud push
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            chmod +x scripts/cf_deploy.sh
            scripts/cf_deploy.sh
          fi
